# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d73385f4ee9d4a59da3e61433ce8978c60fecae273d5bf0a65dd59cb0ec64495beb85f289e2e765775af72ef022dd12b21c7ea7a43a81dbaa8ed283e1ec7026

test:
  secret_key_base: 40d9e823330f63d7c6c4282d39e8f2aafd100b4bceeee59e2113bb9aacb0c0f658184c1dff8554ebe45bc1d2238210cefc0fe62125511449e9a6a1b4bf2ae8be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
